# Generated by Django 4.2 on 2023-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='filial',
            field=models.CharField(choices=[('Institut', 'Institut'), ('Nukus Filiali', 'Nukus Filiali'), ('Samarqand filiali', 'Samarqand filiali'), ("Farg'ona filali", "Farg'ona filali")], max_length=1000, null=True),
        ),
    ]
